name: swiftspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  audioplayers: ^6.6.0
  cached_network_image: ^3.4.1
  chewie: ^1.13.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  get_it: ^9.2.1
  google_fonts: ^8.0.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  latlong2: ^0.9.1
  lucide_icons: ^0.257.0
  panorama_viewer: ^2.0.7
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  share_plus: ^12.0.2
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.12.2
  url_launcher: ^6.3.2
  uuid: ^4.5.3
  video_player: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
